---
openapi: 3.0.0
info:
  version: 1.0.0
  title: Some API
  description: ''
security: []
tags:
- name: TemplateSerializer
  description: TimeTrackerTemplate Serializer
- name: Templates
  description: TimeTrackerTemplates Controller
paths:
  "/internal_api/time_tracker_templates":
    get:
      summary: Index
      operationId: Templates_Index
      tags:
      - Templates
      description: Get up to 15 TimeTrackerTemplates
      responses:
        success:
          description: TimeTrackerTemplates returned
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/TimeTrackerTemplateSerializer"
    post:
      summary: Create
      operationId: Templates_Create
      tags:
      - Templates
      description: Create new TimeTrackerTemplate
      responses:
        success:
          description: TimeTrackerTemplate created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/TimeTrackerTemplateSerializer"
  "/internal_api/time_tracker_templates/{id}":
    delete:
      summary: Destroy
      operationId: Templates_Destroy
      tags:
      - Templates
      description: Destroy existing TimeTrackerTemplate
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        success:
          description: TimeTrackerTemplate destroyed
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/TimeTrackerTemplateSerializer"
  "/internal_api/time_tracker_templates/{id}/apply":
    put:
      summary: Apply
      operationId: Templates_Apply
      tags:
      - Templates
      description: Start TimeTracker from TimeTrackerTemplate
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        success:
          description: TimeTracker created with TimeTrackerTemplate
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/TimeTrackerTemplateSerializer"
components:
  schemas:
    TimeTrackerTemplateSerializer:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: integer
        timetracking_category_id:
          type: integer
        timetracking_subcategory_id:
          type: integer
        project_phase_id:
          type: integer
        name:
          type: string
